name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres_test

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true

    - name: Install PostgreSQL dependencies
      run: sudo apt-get install -y libpq-dev

    - name: Install Dependencies
      working-directory: backend
      run: |
        gem install bundler
        bundle config set force_ruby_platform true
        bundle install

    - name: Run Brakeman (Security Linter)
      working-directory: backend
      run: bundle exec brakeman --no-pager

    - name: Run RuboCop (Style Linter)
      working-directory: backend
      run: bundle exec rubocop

    - name: Run Rails Best Practices
      working-directory: backend
      run: |
        gem install rails_best_practices
        bundle exec rails_best_practices .

    - name: Setup database
      working-directory: backend
      run: |
        bundle exec rails db:create RAILS_ENV=test
        bundle exec rails db:migrate RAILS_ENV=test

    #- name: Run Tests
    #  working-directory: backend
    #  run: bundle exec rails test